<div align="center">

**LAPORAN PRAKTIKUM**

**STRUKTUR DATA**

**“Tipe Data dan Variable”**

**Disusun Oleh :**

**Muhammad Danish Abshori**

**2611533002**

**Dosen Pengampu:**

**Wahyudi.DR.. S.T.M.T**

**Asisten Praktikum:**

**Sherly Sukmadira**

<br>

 <img src="images/logo_unand.png" width="200">

<br>

**FAKULTAS TEKNOLOGI INFORMASI**

**DEPARTEMEN INFORMATIKA**

**UNIVERSITAS ANDALAS**

**2026**

</div>

## KATA PENGANTAR

Puji syukur penulis panjatkan atas kehadirat Tuhan Yang Maha Esa yang telah memberikan rahmat dan berkatnya, sehingga penulis dapat menyelesaikan laporan praktikum ... yang telah dilaksanakan sebagai pertemuan ke-1 untuk mata kuliah Praktikum Struktur Data. Praktikum ini berfokus pada pembahasan ...

Melalui praktikum ini, hasil yang diharapkan adalah penulis dapat memahami dan mengimplementasikan secara langsung konsep ... pada real project.

Penulis menyadari bahwa laporan praktikum ini masih memiliki banyak kekurangan. Oleh karena itu, kritik dan saran yang membangun sangat diharapkan demi perbaikan dan pengembangan di masa mendatang.

Padang, 2026

---
# BAB I
# PENDAHULUAN

## 1.1 Latar Belakang
Saat ini teknologi informasi banyak digunakan untuk membantu mengolah data dan membuat berbagai
macam sistem. Salah satu bahasa pemrograman yang sering dipakai adalah Python. Bahasa ini cukup
ramah bagi pemula karena penulisannya sederhana dan mudah dibaca. Python juga dapat digunakan untuk
membuat aplikasi, mengolah data, melakukan otomatisasi, sampai mengembangkan kecerdasan buatan.
Oleh karena itu, mempelajari dasar Python menjadi salah satu langkah penting sebelum masuk ke materi
pemrograman yang lebih lanjut.

Dalam pemrograman, variabel mempunyai peran sebagai tempat menyimpan suatu nilai. Nilai tersebut dapat
dipakai kembali atau diolah selama program berjalan. Penggunaan variabel membuat data di dalam program
menjadi lebih mudah dikelola.
Selain variabel, tipe data juga perlu dipahami. Tipe data digunakan untuk menunjukkan jenis nilai yang
disimpan, seperti `int` untuk bilangan bulat, `float` untuk bilangan desimal, `str` untuk teks, dan `boolean` untuk
nilai benar atau salah. Python bersifat dynamically typed, sehingga tipe variabel dapat ditentukan
berdasarkan nilai yang diberikan.

Karena variabel dan tipe data merupakan dasar dalam pemrograman, keduanya perlu dipahami sebelum
mempelajari materi yang lebih kompleks. Melalui praktikum ini, diharapkan praktikan mampu menggunakan
variabel, membedakan tipe data dasar, dan membuat program Python sederhana.
## 1.2 Tujuan
1. Memahami penggunaan variabel dalam pemrograman Python.
2. Mengetahui berbagai macam tipe data yang terdapat pada Python.
3. Mampu membuat deklarasi variabel serta melakukan perubahan tipe data.
4. Memahami cara menemukan dan menangani kesalahan pada program.

## 1.3 Manfaat
1. Membantu memahami dasar-dasar pemrograman menggunakan Python.
2. Meningkatkan kemampuan dalam membuat dan menjalankan program secara langsung.
3. Membantu mengurangi kesalahan saat menulis dan mengembangkan kode program.

---
# BAB II
# PEMBAHASAN

## 2.1 Dasar Teori
1. Mengenal Bahasa Pemrograman Python

Python adalah bahasa pemrograman tingkat tinggi yang bersifat interpreted, object-oriented, dan
dynamically typed. Bahasa ini dikembangkan oleh Guido van Rossum dan pertama kali diperkenalkan pada
tahun 1991. Python memiliki bentuk penulisan yang relatif sederhana sehingga mudah dibaca dan dipelajari.
Penggunaannya cukup luas, mulai dari pembuatan aplikasi, otomatisasi pekerjaan, pengolahan data, hingga
kecerdasan buatan.

2. Variabel pada Python

Variabel dapat dianggap sebagai tempat untuk menaruh sebuah nilai agar nilai tersebut dapat digunakan di
dalam program. Pada Python, variabel bisa langsung dibuat dengan menggunakan tanda `=` tanpa
menuliskan tipe data terlebih dahulu. Ada beberapa aturan dalam membuat nama variabel, misalnya huruf
besar dan kecil dianggap berbeda, nama variabel tidak boleh diawali angka, dan kata yang sudah menjadi
keyword Python tidak boleh digunakan sebagai nama variabel.
3. Tipe Data Dasar

Tipe data menunjukkan bentuk atau jenis nilai yang terdapat pada suatu variabel. Beberapa tipe data dasar
yang sering digunakan dalam Python antara lain:
• **Integer (`int`)**: untuk bilangan bulat, contohnya `-5`, `0`, dan `100`.
• **Float (`float`)**: untuk bilangan yang mempunyai angka di belakang koma, contohnya `3.14` dan `-0.01`.
• **String (`str`)**: untuk menyimpan teks atau kumpulan karakter yang ditulis di dalam tanda petik,
contohnya `"Praktikum Python"`.
• **Boolean (`bool`)**: untuk menyimpan nilai logika, yaitu `True` atau `False`.

## 2.2 Kode Program

### 2.2.1 Program "Boolean_2611533002.py"


In [1]:
# Buat file dengan nama Boolean_2611533002.py
# Nama variable ditambah 4 digit nim terakhir contoh: nilai_1234
# Deklarasikan variable dengan type Boolean
is_lulus_3002 = True
is_cumlaude_3002 = True

# Menggunakan Boolean
nilai_3002 = 80
batas_lulus_3002 = 75

#Menentukan nilai Boolean dari kondisi
status_kelulusan_3002 = nilai_3002 >= batas_lulus_3002 # Hasilnya akan True

print("=== Check Kelulusan ===")
print("Nilai", nilai_3002)
print("Apakah Lulus?", status_kelulusan_3002)
if is_lulus_3002 and is_cumlaude_3002:
    print("Selamat, Anda lulus dengan predikat Cumlaude!")

=== Check Kelulusan ===
Nilai 80
Apakah Lulus? True
Selamat, Anda lulus dengan predikat Cumlaude!


**Penjelasan :**
1. Dua variabel pertama berisi nilai Boolean untuk menunjukkan status lulus dan status cumlaude.
2. `nilai_3002` menyimpan nilai mahasiswa, sedangkan `batas_lulus_3002` menyimpan nilai minimum untuk
dinyatakan lulus.
3. Perbandingan kedua nilai tersebut menghasilkan `True` atau `False` pada variabel status kelulusan.
4. Hasil akhirnya ditampilkan ke layar menggunakan beberapa perintah `print()`.

### 2.2.2 Program Driver "Input_2611533002.py"

In [3]:
# Buat file dengan nama Input_2611533002.py
# Buat Program untuk menghitung luas persegi panjang
# Nama variable ditambah 4 digit nim terakhir contoh: panjang_1234
# Program ini menggunakan fungsi input() untuk meminta pengguna
# memasaukan nilai panjang dan lebar persegi panjang
# Nilai yang dimasukin akan dikonversi menjadi tipe data integer
panjang_3002 = input("Masukan panjang: ")
lebar_3002 = input("Masukan lebar: ")
luas_3002 = int(panjang_3002) * int(lebar_3002)
print("luas = ", luas_3002)

luas =  24


**Penjelasan:**

 1. Program meminta pengguna mengisi panjang dan lebar persegi panjang melalui `input()`.
2. Kedua input diubah menjadi bilangan integer, lalu dikalikan untuk mendapatkan luas.
3. Hasil luas yang sudah dihitung ditampilkan pada layar.

### 2.2.3 Program "Konstanta_2611533002.py"

In [4]:
# Buat file dengan nama Konstanta_2611533002.py
# Program ini menggunakan konstanta untuk menghitung luas lingkaran
# nama variable ditambah 4 digit nim terakhir contoh: phi_1234

from typing import Final
PI : Final = 3.14
print("pi: %f" % (PI))
jari_3002 = float(input("Masukan jari-jari lingkaran: "))
luas_3002 = PI * jari_3002 * jari_3002
print("Luas lingkaran dengan jari-jari %.2f adalah %.2f"% (jari_3002, luas_3002))

pi: 3.140000
Luas lingkaran dengan jari-jari 8.00 adalah 200.96


**Penjelasan:**

1. Program mengimpor `Final` dan menetapkan `PI` dengan nilai 3.14 sebagai konstanta.
2. Nilai PI ditampilkan, kemudian pengguna diminta memasukkan jari-jari lingkaran.
3. Nilai jari-jari digunakan bersama PI untuk menghitung luas lingkaran.
4. Hasil perhitungan ditampilkan dengan dua angka di belakang koma.

### 2.2.4 Program "Numerik_261153302.py"

In [ ]:
# Buat dile dengan nama Numerik_22611533002.py
#create a variabel with integer float value
a_3002=100
print("The type of variable having value", a_3002, " is ", type(a_3002))

#create a variable with float value.0
b_3002=10.2345
print("The type of variable having valeu", b_3002, " is ", type(b_3002))

#create a variable with complex value.

c_3002=100+3j
print("The type of variable having value", c_3002, " is ", type(c_3002))

The type of variable having value 100  is  <class 'int'>
The type of variable having valeu 10.2345  is  <class 'float'>
The type of variable having value (100+3j)  is  <class 'complex'>


**Penjelasan:**

1. Variabel `a_3002` diisi dengan bilangan bulat 100, lalu tipe datanya diperiksa menggunakan `type()`.
2. Variabel `b_3002` berisi nilai desimal 10.2345 dan program menampilkan tipe datanya.
3. Variabel `c_3002` berisi bilangan kompleks `100+3j`, kemudian tipe datanya juga diperiksa.

### 2.2.5 Program "String_2611533002.py"


In [ ]:
# Buat file dengan nama String_2611533002.py
#nama variable ditambah 4 digit nim terakhir contoh:nama_1234
#ganti program dan data masing2
nama = "Muhammad Danish Abshori_2611533002"
jenis_kelamin = 'L'
alamat = """
    Desa Simpang Empat
    Kec. Danau Kerinci
    Kab. Kerinci
"""
agama = 'Islam'
print("Nama saya adalah", nama)
print("Jenis kelamin saya adalah", jenis_kelamin)
print("Alamat saya adalah", alamat)
print("Agama saya adalah", agama)

Nama saya adalah Muhammad Danish Abshori_2611533002
Jenis kelamin saya adalah L
Alamat saya adalah 
    Desa Simpang Empat
    Kec. Danau Kerinci
    Kab. Kerinci

Agama saya adalah Islam


**Penjelasan:**

1. Program membuat variabel untuk menyimpan nama dan jenis kelamin.
2. Data alamat disimpan pada variabel `alamat_3002` dalam bentuk string yang terdiri dari beberapa baris.
3. Variabel `agama_3002` digunakan untuk menyimpan informasi agama.
4. Semua data tersebut kemudian ditampilkan satu per satu menggunakan `print()`

---
# BAB III
# KESIMPULAN

Setelah melakukan praktikum Algoritma dan Pemrograman mengenai tipe data dan variabel, beberapa hal
yang dapat disimpulkan adalah sebagai berikut:

1. Python: Python mempunyai aturan penulisan yang cukup sederhana sehingga cocok untuk mempelajari
dasar pemrograman dan membuat program dengan berbagai kebutuhan.

2. Tempat Menjalankan Program: VS Code dan Google Colab dapat digunakan untuk menulis,
menjalankan, serta mencoba program Python. Keduanya membantu proses praktik menjadi lebih mudah.

3. Git dan GitHub: Git dan GitHub dapat dimanfaatkan untuk menyimpan serta mengelola kode program.
Perintah seperti `git init`, `add`, `commit`, dan `push` digunakan dalam proses pengelolaan perubahan dan
penyimpanan kode ke repositori.


---
## DAFTAR PUSTAKA

[1] ■Lubanovic, B. (2019). Introducing Python: Modern Computing in Simple Packages (2nd ed.). O'Reilly
Media. Link: https://www.oreilly.com/library/view/introducing-python-2nd/9781492051374/

[2] ■Matthes, E. (2019). Python Crash Course: A Hands-On, Project-Based Introduction to Programming
(2nd ed.). No Starch Press. Link: https://nostarch.com/pythoncrashcourse2e

[3] ■Severance, C. R. (2016). Python for Everybody: Exploring Data in Python 3. CreateSpace Independent
Publishing Platform. Link: https://www.py4e.com/book

[4] ■Swaroop, C. H. (2013). A Byte of Python. Link: https://python.swaroopch.com/